### ISSUE TITLE
pkt.Idx maybe overstep the array boundary in WritePacket function

### ISSUE THREAD

**Issue by ismjt** [deepch/vdk#1]
when i use hikvision RTSP url in my demo, the following code will cause exception. In my case, when pkt.Idx=1, but len(element.streams) is still 1.

https://github.com/deepch/vdk/blob/087a2b4c2d63ffa4a07adba8cc7c15cc6e6d8415/format/mp4f/muxer.go#L256

my fix is
```
if int(pkt.Idx) >= len(element.streams) {
  return false, []byte{}, fmt.Errorf("pkt's Idx is array bound ")
}
stream := element.streams[pkt.Idx]	
```
and it's work.

**Comment by deepch** [comment]
You can give access to the camera so I can check what the problem is.
