### ISSUE TITLE
关于h264问题

### ISSUE THREAD

**Issue by workyu** [deepch/vdk#10]
是否可以提供一个h264解码后,抽取一帧转图片的功能

**Comment by deepch** [comment]
是的，你可以做這個例子是

https://github.com/livepeer/stream-tester/tree/a4a99484169bc130fe14fd8264eef9776b1a6b27/internal/codec

**Comment by workyu** [comment]
> 是的，你可以做这个例子是
> 
> https://github.com/livepeer/stream-tester/tree/a4a99484169bc130fe14fd8264eef9776b1a6b27/internal/codec

ok,谢谢

**Comment by deepch** [comment]
@workyu 不客气
