### ISSUE TITLE
need documentation :) How to save a stream?

### ISSUE THREAD

**Issue by dottgonzo** [deepch/vdk#11]
Hi,
thanks for sharing this code, it is awesome!
I'm try to hack it a bit, but unfortunately i'm not a golang pro coder, so i'm not able to understand how to save the stream (the source as flv or the wp8 generated) and i don't understand if this libs is transcoding the stream (when it is possible and needed) or mp4 rtsp media streams is repackaged to an webrtc container when codec match the ones supported without transcoding (or both).

can you help me to understand which method/library i need to use to store the (source) stream in chunks?

**Comment by deepch** [comment]
https://github.com/deepch/RTSPtoWebRTC/issues/46

closed
