### ISSUE TITLE
how to save a packet data into a png or jpeg image ?

### ISSUE THREAD

**Issue by tangtang666** [deepch/vdk#12]
type Packet struct {
	IsKeyFrame      bool          // video packet is key frame
	Idx             int8          // stream index in container format
	CompositionTime time.Duration // packet presentation time minus decode time for H264 B-Frame
	Time            time.Duration // packet decode time
	Data            []byte        // packet data
}

**I want to know the Data is a nv12 or yuv data?**

**Comment by deepch** [comment]
yuv

**Comment by tangtang666** [comment]
> yuv

Thanks for your reply.I find the lengths of the KeyFrame pkt.Data always not equal，and the Y channel is not equal width*height。Follow is my code to save the yuv data to jpeg。how i can to save it？
```
// pkt.Data is yuv
width := 1920
height := 1080
yuv_byte := pkt.Data[4:]
fmt.Println("yuv_byte len:",len(yuv_byte))
img := image.NewYCbCr(image.Rect(0, 0, width, height), image.YCbCrSubsampleRatio420)
img.Y = yuv_byte
//img.Cb = pkt.Data
//img.Cr = pkt.Data
jpg, _ := os.Create("yuv.jpg")
jpeg.Encode(jpg, img, nil)
```

**Comment by deepch** [comment]
oh no you need decode video to image look FFmpeg decode to jpeg

1. Create frame 00 00 00 01 SPS 00 00 00 01 PPS 00 00 00 01 IFRAME (look is IsKeyFrame)
2. Send key frame h264decoder and decode Frame write as jpeg

look code 

https://github.com/deepch/vdk/blob/fccce247d0965d6a68f26307e97ef27bf53321c8/cgo/ffmpeg/video.go#L62

**Comment by tangtang666** [comment]
> vdk / cgo / ffmpeg / video.go



> oh no you need decode video to image look FFmpeg decode to jpeg
> 
> Custom decode sample
> 
> 1. Create frame 00 00 00 01 SPS 00 00 00 01 PPS 00 00 00 01 IFRAME (look is IsKeyFrame)
> 2. Send key frame h264decoder and encod  as jpeg
> 
> or use NewVideoDecoder and Decode
> 
> look code
> 
> https://github.com/deepch/vdk/blob/fccce247d0965d6a68f26307e97ef27bf53321c8/cgo/ffmpeg/video.go#L62

Thanks,I know your means, but it's not my intention。Now I had use gocv to make some functions，and It‘s not convenient to deploy,so i find the vdk module.Finally I use (muxer.WritePacket) send three package to html solve it。If I have free time, I will continue  to solve this problem through golang.
