### ISSUE TITLE
writeSetChunkSize too big.

### ISSUE THREAD

**Issue by cgoder** [deepch/vdk#16]
https://github.com/deepch/vdk/blob/fccce247d0965d6a68f26307e97ef27bf53321c8/format/rtmp/rtmp.go#L357

push stream to rtmp server. will be error as: 

`2021/03/10 09:20:50 [alert] 8#8: *10 too big RTMP chunk size:134217728, client: 172.17.0.1, server: 0.0.0.0:1935
2021/03/10 09:21:14 [alert] 8#8: *11 too big RTMP chunk size:134217728, client: 172.17.0.1, server: 0.0.0.0:1935`

and connect to play this stream be reject. return EOF.

**Comment by cgoder** [comment]
AND, set the chunksize with 1024,or 128*1024 is ok.

**Comment by deepch** [comment]
Thank you so much, I will fix this in the next release.
