### ISSUE TITLE
Implementation of protocols other than tcp for rtsp

### ISSUE THREAD

**Issue by avmayorov** [deepch/vdk#2]
Hello,

You've created a cool library.

Do you have plans to implement other protocols (udp, http) than tcp for rtsp?

**Comment by deepch** [comment]
In fact, I just combined several projects.
Yes, I can add udp to rtsp.
but maybe right now a more urgent question is to add h265


in my examples you can find

rtsp -> ws
rtsp -> webRTC (I'm currently migrating to VDK && Pion API)

**Comment by avmayorov** [comment]
Thanks for answer

**Comment by ayazhussein** [comment]
any updates on this, I see that it is still on TCP and there is no option for UDP in rtspv2 package.

**Comment by Cacsjep** [comment]
I am also interrested for UDP Transport for rtsp, btw. Awesome work
