### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by dolwin** [deepch/vdk#4]
```
panic: runtime error: makeslice: len out of range

goroutine 19 [running]:
github.com/deepch/vdk/format/rtsp.(*Client).findRTSP(0xc0004b4000, 0xc000012500, 0x2406, 0x2500, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/glasssky001/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20200419065055-420338e0cc50/format/rtsp/client.go:443 +0x75a
github.com/deepch/vdk/format/rtsp.(*Client).poll(0xc0004b4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/glasssky001/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20200419065055-420338e0cc50/format/rtsp/client.go:536 +0x7d
github.com/deepch/vdk/format/rtsp.(*Client).readPacket(0xc0004b4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/glasssky001/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20200419065055-420338e0cc50/format/rtsp/client.go:1204 +0x84
github.com/deepch/vdk/format/rtsp.(*Client).ReadPacket(0xc0004b4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x140, 0x150)
	/Users/glasssky001/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20200419065055-420338e0cc50/format/rtsp/client.go:1228 +0x90
main.serveStreams.func1(0xc00012a886, 0x2, 0xc00016e180, 0x40)
	/Users/glasssky001/GitHub/RTSPtoWebRTC/stream.go:36 +0x484
created by main.serveStreams
	/Users/glasssky001/GitHub/RTSPtoWebRTC/stream.go:12 +0x12c
```

**Comment by deepch** [comment]
Can you give an example of your stream?

**Comment by NameOfGoy** [comment]
> Can you give an example of your stream?

where the stream(rtsp) has been opened for long time , I can't give a certain time , but almost over 1 day. The problem above will heppen .

**Comment by NameOfGoy** [comment]
> Can you give an example of your stream?

When the stream(rtsp) has been opened for long time , I can't give a certain time , but almost over 1 day. The problem above will heppen .

**Comment by dolwin** [comment]
@deepch  this is my test stream address
```
rtsp://admin:kld123456@wekan.cn:50019/h264/ch1/main/av_stream
```

**Comment by yellow-sky** [comment]
panic: runtime error: makeslice: len out of range

goroutine 15 [running]:
github.com/deepch/vdk/format/rtsp.(*Client).findRTSP(0xc0002da000, 0xc000051ce0, 0x8a491e, 0xbfd8c493963b25a2, 0x315b12016b59, 0x10d3aa0, 0xbfd8c491cdac862c, 0x3159683745ac, 0x10d3aa0)
        /root/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20191130205321-087a2b4c2d63/format/rtsp/client.go:443 +0x755
github.com/deepch/vdk/format/rtsp.(*Client).poll(0xc0002da000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20191130205321-087a2b4c2d63/format/rtsp/client.go:536 +0x7d
github.com/deepch/vdk/format/rtsp.(*Client).readPacket(0xc0002da000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20191130205321-087a2b4c2d63/format/rtsp/client.go:1205 +0x84
github.com/deepch/vdk/format/rtsp.(*Client).ReadPacket(0xc0002da000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x400, 0x470)
        /root/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20191130205321-087a2b4c2d63/format/rtsp/client.go:1229 +0x90

**Comment by deepch** [comment]
try rtsp v2 https://github.com/deepch/vdk/blob/master/format/rtspv2/client.go

**Comment by deepch** [comment]
try rtspv2 example 

https://github.com/deepch/RTSPtoWebRTC/blob/a145ee2cdd2099ceeb02b22080addd6aba1f68a8/stream.go#L33

**Comment by yellow-sky** [comment]
Thx!

**Comment by deepch** [comment]
> Thx!

worked?
