### ISSUE TITLE
How to disable video stream only from video,audio stream

### ISSUE THREAD

**Issue by Saviio** [deepch/vdk#43]
Hi @deepch，

I'm a new to rtsp protocol user, in my scenario I wanna re-stream audio only from video, audio stream.

I have tried to add option: disableVideo and skipped video track request, but it seems doesn't works.  I got nothing from tcp, and  a error was found: read tcp i/o timeout.

would you have any suggestion?

**Comment by deepch** [comment]
1) not setup video or audio
2) ignore idx video or audio and delete codecs slice idx
