### ISSUE TITLE
Duration for rtspv2 not calculated properly.

### ISSUE THREAD

**Issue by d21d3q** [deepch/vdk#51]
Related to https://github.com/deepch/RTSPtoWebRTC/issues/121#issuecomment-1062719034

Packets inspected [here](https://github.com/deepch/RTSPtoWebRTC/blob/f4bc2f27cb9c085cee9c7d06cad9c43b8754d50c/http.go#L147) are having negative duration. 
Video is stuttering, `about:webrtc` reports framerate around, 3. 

after abs'ing Duration` before sending

```
if pck.Duration < 0 {
	pck.Duration = -pck.Duration
}
err = muxerWebRTC.WritePacket(pck)
```
frame rate reported in `about:webrtc` is around 23. Video is "smoother" - all frames seem to be displayed, they are jumping but in different way (back and forth), I guess that is because `Duration`s is not correct.

**Comment by deepch** [comment]
you can calculate the duration yourself to make it more correct.

Not all cameras give their fps

use formula 

pck.Duration = 1000/fps

you can get the perfect picture

**Comment by deepch** [comment]
But if the problem is in the negative duration it is related to reaching the maximum number of numbers and then it jumps to 0, I will fix it.
