### ISSUE TITLE
Compilation terminated on RTSPtoImage app starting

### ISSUE THREAD

**Issue by mirumyantsev** [deepch/vdk#58]
Hi,

Here is the logs:

```
# github.com/deepch/vdk/cgo/ffmpeg
In file included from ../../../../pkg/mod/github.com/deepch/vdk@v0.0.0-20220402115557-02504b116966/cgo/ffmpeg/audio.go:4:
./ffmpeg.h:2:10: fatal error: libavformat/avformat.h: No such file or directory
    2 | #include <libavformat/avformat.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by deepch** [comment]
if you need decode encode transcode download libavformat apt-get install ....

**Comment by MrPomidoro** [comment]
installing this **libavformat** does not solve the problem

In file included from ../../../../pkg/mod/github.com/deepch/vdk@v0.0.19/cgo/ffmpeg/audio.go:4:
./ffmpeg.h:5:10: fatal error: libavresample/avresample.h: No such file or directory
    5 | #include <libavresample/avresample.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
